/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Animation: typeof import('./src/shared/ui/animation/Animation.vue')['default']
    Button: typeof import('./src/shared/ui/button/Button.vue')['default']
    Icon: typeof import('./src/shared/ui/icon/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/shared/ui/select/Select.vue')['default']
  }
}
