services:
  postgres:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: ${DB_DATA_PATH}
    volumes:
      - ./api/postgres-data:/data/postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context: ./api
    working_dir: /app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - ./api:/app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: sh -c "air"
    depends_on:
      - postgres
  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    build:
      context: .
    working_dir: /app
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_PORT}
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    command: sh -c "pnpm run dev"