[build]
  cmd = "go build -o main main.go"
  bin = "main"
  dir = "."
  include_ext = ["go"]
  exclude_dir = ["vendor", "postgres-data"]
  run_after_build = "chmod +x main"
  poll = true

[log]
  level = "debug"
